package model;

/*
* QUESTA INTERFACCIA, IMPLEMENTATA DA GAME, CONTIENE TUTTI I METODI CHE POSSONO ESSERE UTILIZZATI DIRETTAMENTE DAL CLIENT (ES-> PEESCA UNA PESCA)
* NON SONO CONTENUTI I METODI RELATIVI AD ALTRO -> GETTER, SETTER
* NEL GAME, INVECE, CI SONO TUTTI I METODI (ES-> ASSEGNAZIONE CARTE OBIETTIVO COMUNI, FIRST CARD, CREAZIONE TABELLONE DEI PUNTI ECC..
* */


public interface WhatCanPlayerDo {
}
